"""create mvp tables fonts devices device_fonts sync_queue

Revision ID: 23e4bc1a6af9
Revises:
Create Date: 2026-03-08 14:00:40.291289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23e4bc1a6af9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('hostname', sa.String(length=200), nullable=False),
    sa.Column('os', sa.String(length=50), nullable=False),
    sa.Column('os_version', sa.String(length=100), nullable=True),
    sa.Column('agent_version', sa.String(length=20), nullable=True),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_sync_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('sync_status', sa.String(length=20), server_default=sa.text("'idle'"), nullable=False),
    sa.Column('font_directories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('auto_pull', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fonts',
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_format', sa.String(length=10), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('family_name', sa.String(length=500), nullable=True),
    sa.Column('subfamily_name', sa.String(length=200), nullable=True),
    sa.Column('full_name', sa.String(length=500), nullable=True),
    sa.Column('postscript_name', sa.String(length=500), nullable=True),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('designer', sa.String(length=500), nullable=True),
    sa.Column('manufacturer', sa.String(length=500), nullable=True),
    sa.Column('license', sa.Text(), nullable=True),
    sa.Column('license_url', sa.String(length=1000), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight_class', sa.Integer(), nullable=True),
    sa.Column('width_class', sa.Integer(), nullable=True),
    sa.Column('is_italic', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_oblique', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('panose', sa.String(length=30), nullable=True),
    sa.Column('classification', sa.String(length=50), nullable=True),
    sa.Column('unicode_ranges', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('supported_scripts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('glyph_count', sa.Integer(), nullable=True),
    sa.Column('is_variable', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('variable_axes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_device_id', sa.UUID(), nullable=True),
    sa.Column('google_fonts_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    op.create_index('ix_fonts_classification', 'fonts', ['classification'], unique=False)
    op.create_index('ix_fonts_deleted_at', 'fonts', ['deleted_at'], unique=False)
    op.create_index('ix_fonts_family_name', 'fonts', ['family_name'], unique=False)
    op.create_index('ix_fonts_file_hash', 'fonts', ['file_hash'], unique=False)
    op.create_index('ix_fonts_source', 'fonts', ['source'], unique=False)
    op.create_index('ix_fonts_supported_scripts', 'fonts', ['supported_scripts'], unique=False, postgresql_using='gin')
    op.create_table('device_fonts',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('font_id', sa.UUID(), nullable=False),
    sa.Column('local_path', sa.String(length=1000), nullable=False),
    sa.Column('installed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['font_id'], ['fonts.id'], ),
    sa.PrimaryKeyConstraint('device_id', 'font_id')
    )
    op.create_table('sync_queue',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('font_id', sa.UUID(), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['font_id'], ['fonts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_queue')
    op.drop_table('device_fonts')
    op.drop_index('ix_fonts_supported_scripts', table_name='fonts', postgresql_using='gin')
    op.drop_index('ix_fonts_source', table_name='fonts')
    op.drop_index('ix_fonts_file_hash', table_name='fonts')
    op.drop_index('ix_fonts_family_name', table_name='fonts')
    op.drop_index('ix_fonts_deleted_at', table_name='fonts')
    op.drop_index('ix_fonts_classification', table_name='fonts')
    op.drop_table('fonts')
    op.drop_table('devices')
    # ### end Alembic commands ###
