"""baseline sqlite schema

Revision ID: fbca947b83c5
Revises: 
Create Date: 2026-06-16 13:53:14.154764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbca947b83c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('hostname', sa.String(length=200), nullable=False),
    sa.Column('os', sa.String(length=50), nullable=False),
    sa.Column('os_version', sa.String(length=100), nullable=True),
    sa.Column('agent_version', sa.String(length=20), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('font_directories', sa.JSON(), nullable=True),
    sa.Column('auto_pull', sa.Boolean(), nullable=False),
    sa.Column('auto_push', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('font_families',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=500), nullable=False),
    sa.Column('designer', sa.String(length=500), nullable=True),
    sa.Column('manufacturer', sa.String(length=500), nullable=True),
    sa.Column('classification', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('style_count', sa.Integer(), nullable=False),
    sa.Column('is_auto_grouped', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('font_families', schema=None) as batch_op:
        batch_op.create_index('ix_font_families_name', ['name'], unique=False)
        batch_op.create_index('ix_font_families_slug', ['slug'], unique=False)

    op.create_table('fonts',
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_format', sa.String(length=10), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('family_name', sa.String(length=500), nullable=True),
    sa.Column('subfamily_name', sa.String(length=200), nullable=True),
    sa.Column('full_name', sa.String(length=500), nullable=True),
    sa.Column('postscript_name', sa.String(length=500), nullable=True),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('designer', sa.String(length=500), nullable=True),
    sa.Column('manufacturer', sa.String(length=500), nullable=True),
    sa.Column('license', sa.Text(), nullable=True),
    sa.Column('license_url', sa.String(length=1000), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight_class', sa.Integer(), nullable=True),
    sa.Column('width_class', sa.Integer(), nullable=True),
    sa.Column('is_italic', sa.Boolean(), nullable=False),
    sa.Column('is_oblique', sa.Boolean(), nullable=False),
    sa.Column('panose', sa.String(length=30), nullable=True),
    sa.Column('classification', sa.String(length=50), nullable=True),
    sa.Column('unicode_ranges', sa.JSON(), nullable=True),
    sa.Column('supported_scripts', sa.JSON(), nullable=True),
    sa.Column('glyph_count', sa.Integer(), nullable=True),
    sa.Column('is_variable', sa.Boolean(), nullable=False),
    sa.Column('variable_axes', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_device_id', sa.Uuid(), nullable=True),
    sa.Column('google_fonts_id', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    with op.batch_alter_table('fonts', schema=None) as batch_op:
        batch_op.create_index('ix_fonts_classification', ['classification'], unique=False)
        batch_op.create_index('ix_fonts_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('ix_fonts_family_name', ['family_name'], unique=False)
        batch_op.create_index('ix_fonts_file_hash', ['file_hash'], unique=False)
        batch_op.create_index('ix_fonts_source', ['source'], unique=False)

    op.create_table('device_fonts',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('font_id', sa.Uuid(), nullable=False),
    sa.Column('local_path', sa.String(length=1000), nullable=False),
    sa.Column('activated', sa.Boolean(), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['font_id'], ['fonts.id'], ),
    sa.PrimaryKeyConstraint('device_id', 'font_id')
    )
    op.create_table('font_family_members',
    sa.Column('font_id', sa.Uuid(), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['font_families.id'], ),
    sa.ForeignKeyConstraint(['font_id'], ['fonts.id'], ),
    sa.PrimaryKeyConstraint('font_id')
    )
    with op.batch_alter_table('font_family_members', schema=None) as batch_op:
        batch_op.create_index('ix_font_family_members_family_id', ['family_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('font_family_members', schema=None) as batch_op:
        batch_op.drop_index('ix_font_family_members_family_id')

    op.drop_table('font_family_members')
    op.drop_table('device_fonts')
    with op.batch_alter_table('fonts', schema=None) as batch_op:
        batch_op.drop_index('ix_fonts_source')
        batch_op.drop_index('ix_fonts_file_hash')
        batch_op.drop_index('ix_fonts_family_name')
        batch_op.drop_index('ix_fonts_deleted_at')
        batch_op.drop_index('ix_fonts_classification')

    op.drop_table('fonts')
    with op.batch_alter_table('font_families', schema=None) as batch_op:
        batch_op.drop_index('ix_font_families_slug')
        batch_op.drop_index('ix_font_families_name')

    op.drop_table('font_families')
    op.drop_table('devices')
    # ### end Alembic commands ###
